# Generated by Django 3.1.4 on 2022-07-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Years_of_Experience', models.CharField(max_length=60)),
                ('Company', models.CharField(max_length=60)),
                ('Position', models.CharField(max_length=60)),
                ('Department', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
                ('City', models.CharField(max_length=60)),
            ],
        ),
    ]
